---
title: "Technical Report"
author: "Hazel Ethier and Eva Gerstle"
date: "4/19/2018"
output: pdf_document
---

\newpage

```{r include=FALSE, message=FALSE}
library(tidyverse)
library(ipumsr)
library(mosaic)
library(Stat2Data)
library(dplyr)
library(ggplot2)
library(lmtest)
setwd("~/Desktop")

project_ddi <- read_ipums_ddi("usa_00005.xml")
project_data <- read_ipums_micro(project_ddi, verbose = FALSE)

```

```{r}
project_data <- project_data %>%
  mutate(
    Northeast=if_else(REGION == 11 | REGION == 12, 1 ,0),
    Midwest=if_else(REGION == 21 | REGION == 22, 1, 0),
    South=if_else(REGION == 31 | REGION == 32 | REGION == 33,1,0),
    West=if_else(REGION == 41 | REGION == 42,1,0)
  ) %>%
  mutate(
    white=if_else(RACE == 1,1,0),
    black =if_else(RACE == 2,1,0),
    nativeamerican=if_else(RACE==3,1,0),
    asian=if_else(RACE==4 | RACE==5 | RACE==6,1,0),
    otherrace=if_else(RACE==7,1,0),
    twoormore=if_else(RACE==8 | RACE == 9,1,0)
  ) %>%
  mutate(
    CINETHH= as.factor(if_else(CINETHH == 1 | CINETHH == 2, 1,0))
  ) %>%
  mutate(
    FARM= as.factor(if_else(FARM == 2, 1,0))
  ) %>%
  mutate(
    SSMC= as.factor(if_else(SSMC == 1 | SSMC == 2, 1,0))
  ) %>%
  mutate(
    MULTGEN= as.factor(if_else(MULTGEN == 3, 1,0))
  ) %>%
  select(PERNUM, SERIAL, Northeast, Midwest, South, West, AGE, RACE, SSMC, FARM, CINETHH, MULTGEN, HHINCOME, NCHLT5, white, black, nativeamerican, asian, otherrace, twoormore, NUMPREC)
str(project_data, give.attr = FALSE)
```
#Introduction

  
#Results

##Primary Question 

```{r}
primarymodel <- glm(MULTGEN ~ West + Midwest + South + AGE + HHINCOME + NUMPREC + NCHLT5 + NUMPREC*NCHLT5 + FARM + black + nativeamerican + asian +otherrace + twoormore , family=binomial, data = project_data)
summary(primarymodel)
```
```{r}
exp(coef(primarymodel))
```

```{r}
#Likelihood Test for Interaction Between Number of Children Under 5 and Number of People in the House

model2<- glm(MULTGEN ~ West + Midwest + South + AGE + HHINCOME + NUMPREC + NCHLT5 + FARM + black + nativeamerican + asian +otherrace + twoormore , family=binomial, data = project_data)

lrtest(model2, primarymodel)
```
```{r}
primarymodel2<-glm(MULTGEN ~ AGE + HHINCOME + NUMPREC + NCHLT5 + NUMPREC*NCHLT5 + FARM + black + nativeamerican + asian +otherrace + twoormore , family=binomial, data = project_data)
lrtest(primarymodel2, primarymodel)
```

##Secondary Question

##Tertiary Question
```{r, echo=FALSE}
tertiarydata <- project_data %>%
  filter(MULTGEN == 1)


justincomeplot <- ggplot(tertiarydata, aes(x=NUMPREC, y= HHINCOME)) + geom_jitter(alpha =.1, color ="blue") 
justincomeplot

m1 <- lm(HHINCOME~NUMPREC, data=tertiarydata)
summary(m1)

modeltertiary <- lm(HHINCOME~NUMPREC + Midwest*NUMPREC + South*NUMPREC + West*NUMPREC + AGE + FARM + NCHLT5 + black*NUMPREC + nativeamerican*NUMPREC + asian*NUMPREC + otherrace*NUMPREC + twoormore*NUMPREC + CINETHH + SSMC, data=tertiarydata)

modeltertiarysmall <- lm(HHINCOME~NUMPREC + Midwest*NUMPREC + South*NUMPREC + West*NUMPREC, data=tertiarydata)
anova(modeltertiarysmall, modeltertiary)
summary(modeltertiarysmall)
summary(modeltertiary)

```
```{r}
tally(~MULTGEN, data=project_data)
```

#Discussion