---
title: "Final Project Data Appendix"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(ipumsr)
library(mosaic)
library(Stat2Data)
library(dplyr)
setwd("~/Desktop")

project_ddi <- read_ipums_ddi("usa_00004.xml")
project_data <- read_ipums_micro(project_ddi, verbose = FALSE)

```

```{r}
project_data <- project_data %>%
  mutate(
    Northeast=if_else(REGION == 11 | REGION == 12, 1 ,0),
    Midwest=if_else(REGION == 21 | REGION == 22, 1, 0),
    South=if_else(REGION == 31 | REGION == 32 | REGION == 33,1,0),
    West=if_else(REGION == 41 | REGION == 42,1,0)
  ) %>%
  mutate(
    white=if_else(RACE == 1,1,0),
    black =if_else(RACE == 2,1,0),
    nativeamerican=if_else(RACE==3,1,0),
    chinese=if_else(RACE==4,1,0),
    japanese=if_else(RACE==5,1,0),
    otherasian=if_else(RACE==6,1,0),
    otherrace=if_else(RACE==7,1,0),
    twomajor=if_else(RACE==8,1,0),
    threeormore=if_else(RACE==9,1,0)
  ) %>%
  mutate(
    CINETHH= as.factor(if_else(CINETHH == 1 | CINETHH == 2, 1,0))
  ) %>%
  mutate(
    FARM= as.factor(if_else(FARM == 2, 1,0))
  ) %>%
  mutate(
    SSMC= as.factor(if_else(SSMC == 1 | SSMC == 2, 1,0))
  ) %>%
  mutate(
    MULTGEN= as.factor(if_else(MULTGEN == 3, 1,0))
  ) %>%
  select(PERNUM, SERIAL, Northeast, Midwest, South, West, RACE, SSMC, FARM, CINETHH, MULTGEN, HHINCOME, NCHLT5, white, black, nativeamerican, chinese, japanese, otherasian, otherrace, twomajor, threeormore)

```

```{r}
str(project_data, give.attr = FALSE)

tally(~Northeast, data=project_data)
tally(~Midwest, data=project_data)
tally(~South, data=project_data)
tally(~West, data=project_data)
tally(~RACE, data=project_data)
tally(~SSMC, data=project_data)
tally(~FARM, data=project_data)
tally(~CINETHH, data=project_data)
tally(~MULTGEN, data=project_data)
favstats(~HHINCOME, data=project_data)
favstats(~NCHLT5, data=project_data)
```

